/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.joergjahnke.gameboy.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int androidgb_sm=0x7f020000;
        public static final int button_a=0x7f020001;
        public static final int button_b=0x7f020002;
        public static final int button_select=0x7f020003;
        public static final int button_start=0x7f020004;
        public static final int cartridge=0x7f020005;
        public static final int exit=0x7f020006;
        public static final int floppy=0x7f020007;
        public static final int folder=0x7f020008;
        public static final int parent=0x7f020009;
        public static final int play=0x7f02000a;
        public static final int settings=0x7f02000b;
        public static final int speedometer_green=0x7f02000c;
        public static final int speedometer_red=0x7f02000d;
        public static final int speedometer_yellow=0x7f02000e;
    }
    public static final class id {
        public static final int antialiasingActive=0x7f050006;
        public static final int exit=0x7f05000e;
        public static final int frameskip=0x7f050000;
        public static final int fs1=0x7f050001;
        public static final int fs2=0x7f050002;
        public static final int fs3=0x7f050003;
        public static final int fs4=0x7f050004;
        public static final int fs5=0x7f050005;
        public static final int load=0x7f05000c;
        public static final int ok=0x7f05000a;
        public static final int orientationSensorActive=0x7f050009;
        public static final int orientationSensorActiveText=0x7f050008;
        public static final int settings=0x7f05000d;
        public static final int soundActive=0x7f050007;
        public static final int text1=0x7f05000b;
    }
    public static final class layout {
        public static final int editsettingsdialog=0x7f030000;
        public static final int listactivities_textview1=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int dlg_active=0x7f040016;
        public static final int dlg_antialiasing=0x7f040019;
        public static final int dlg_frameSkip=0x7f040017;
        public static final int dlg_orientationSensor=0x7f040018;
        public static final int dlg_sound=0x7f040015;
        public static final int menu_about=0x7f040004;
        public static final int menu_exit=0x7f040006;
        public static final int menu_help=0x7f040005;
        public static final int menu_loadCartridge=0x7f040001;
        public static final int menu_pause=0x7f040007;
        public static final int menu_quitGame=0x7f040009;
        public static final int menu_resume=0x7f040008;
        public static final int menu_settings=0x7f040002;
        public static final int menu_showLog=0x7f040003;
        public static final int msg_about=0x7f04000e;
        public static final int msg_cartridgeLoaded=0x7f040011;
        public static final int msg_cartridgeNotLoaded=0x7f040012;
        public static final int msg_couldNotInitialize=0x7f04000f;
        public static final int msg_gameNotSave=0x7f040013;
        public static final int msg_helpNotDisplayed=0x7f040014;
        public static final int msg_notImplemented=0x7f040010;
        public static final int title_about=0x7f04000b;
        public static final int title_cartridgeLoaded=0x7f04000d;
        public static final int title_logMessages=0x7f04000a;
        public static final int title_warning=0x7f04000c;
    }
}
